#! /bin/sh

#
# Keyboard & Cursor
#
setxkbmap -layout es & 
sxhkd &
xsetroot -cursor_name left_ptr &
bspc config pointer_modifier mod1
#	
# Display
#
# wmname LG3D & # for java applications
picom &
feh --no-fehbg --bg-fill ~/perf_linux_src/res_bgrds/dodge-charger-srt-hellcat-2020-4k-mz.jpg &
~/.config/polybar/launch.sh &
dunst &
bspc monitor -d I II III IV V VI 
#
# Windows
#
bspc config border_width         2
bspc config window_gap           5 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


###########################
# CUSTOM
#########################
#
# RULES
#
bspc rule -a xdman-Main state=floating follow=on
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Galculator state=floating follow=on
bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a vlc state=floating follow=on
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Nemo state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Ristretto state=floating follow=on
bspc rule -a Chromium state=floating follow=on
bspc rule -a Psensor state=floating follow=on
bspc rule -a MPlayer state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
#
# STYLES
# Dracula Theme
#
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
# Cyan
#	bspc config active_border_color "#6272a4"
#	bspc config focused_border_color "#8be9fd"
